import type { Metadata } from "next";
import {
  Bricolage_Grotesque,
  Geist_Mono,
  Noto_Sans,
} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--next-font-bricolage-grotesque",
  subsets: ["latin", "vietnamese"],
  weight: "variable",
});

const notoSans = Noto_Sans({
  variable: "--next-font-noto-sans",
  subsets: ["latin", "vietnamese"],
  weight: "variable",
  style: ["normal", "italic"],
});

const geistMono = Geist_Mono({
  variable: "--next-font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        bricolageGrotesque.variable,
        notoSans.variable,
        geistMono.variable,
        "font-sans",
      )}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
